project_name: wty自动化测试

env: 生产环境

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 初七

# 域名1
host: https://www.wanandroid.com
# 域名2，支持多个域名配置
app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
# 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
notification_type: 4

# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 钉钉相关配置
ding_talk:
  webhook:
  secret:

# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: True
  host: prodjq.rwlb.rds.aliyuncs.com
  user: prodwty
  password: 'Prod_Wty123^'
  port: 3306


# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业微信通知的相关配置
wechat:
  webhook:


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍
email:
  send_user:
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key:
  # 收件人改成自己的邮箱
  send_list:

# 飞书通知
lark:
  webhook:
  secret :


feishu:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/69dc685f-3da3-4d47-9fd0-d018c5278ec5
  secret: gw5LXZ0acv5HvBazHblE8

# 服务器连接相关配置
ConnectClient:
#本地服务器31.24
#数据库开关
    Switch: True
    host: 192.168.31.24
    user: lzroot
    password: 123456
    port: 22



